language: python
python:
 - "2.7"
# command to install dependencies
install:
  - cd ..
  - wget http://www.renpy.org/dl/6.99.13/renpy-6.99.13-sdk.tar.bz2
  - tar xf renpy-6.99.13-sdk.tar.bz2
  - rm renpy-6.99.13-sdk.tar.bz2
  - mv renpy-6.99.13-sdk renpy
  - cd sze-the-game/
# command to run tests
script: 
  - ls
  - ../renpy/renpy.sh "./" lint && ../renpy/renpy.sh ../renpy/launcher distribute "./"
